server:
  http_port: ${_SERVER_HTTP_PORT:8080}
  servlet:
    session:
      cookie:
        secure: true

spring:
  main:
    allow-bean-definition-overriding: true
    application:
      name: Earthquakes
    allow-circular-references: true


